"""add ppdb waves fees

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-18 14:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppdb_waves', sa.Column('registration_fee', sa.BigInteger(), nullable=True, server_default='0'))
    op.add_column('ppdb_waves', sa.Column('second_stage_fee', sa.BigInteger(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppdb_waves', 'second_stage_fee')
    op.drop_column('ppdb_waves', 'registration_fee')
    # ### end Alembic commands ###
