version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8000"
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
