import { Button, Card, CardContent, CardHeader, CardTitle } from '@repo/ui'
import type { WALogEntry } from '../../api/client'
import { LOG_STATUSES, formatWhatsAppStatus } from './constants'

interface Props { logs: WALogEntry[]; total: number; totalPages: number; page: number; status: string; loading: boolean; onPage: (page: number) => void; onStatus: (status: string) => void; onRefresh: () => void }

export default function LogsPanel({ logs, total, totalPages, page, status, loading, onPage, onStatus, onRefresh }: Props) {
  return <Card><CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3"><div><CardTitle>Riwayat Pengiriman</CardTitle><p className="mt-1 text-sm text-slate-500">{total} pesan</p></div><div className="flex gap-2"><select aria-label="Filter status" value={status} onChange={e => onStatus(e.target.value)} className="rounded-md border px-2 text-sm">{LOG_STATUSES.map(item => <option key={item} value={item}>{item ? formatWhatsAppStatus(item) : 'Semua status'}</option>)}</select><Button size="sm" variant="outline" onClick={onRefresh}>Perbarui</Button></div></CardHeader><CardContent>{loading ? <p className="py-8 text-center text-sm text-slate-500">Memuat riwayat...</p> : logs.length === 0 ? <p className="py-8 text-center text-sm text-slate-500">Belum ada pesan.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="p-2">Penerima</th><th className="p-2">Nomor</th><th className="p-2">Jenis</th><th className="p-2">Status</th><th className="p-2">Waktu</th></tr></thead><tbody>{logs.map(log => <tr key={log.id} className="border-b last:border-0"><td className="p-2">{log.recipient_name || '—'}</td><td className="p-2">{log.recipient_phone}</td><td className="p-2">{log.event_key}</td><td className="p-2">{formatWhatsAppStatus(log.status)}</td><td className="whitespace-nowrap p-2">{new Date(log.created_at).toLocaleString('id-ID')}</td></tr>)}</tbody></table></div>}<div className="mt-4 flex items-center justify-between"><Button size="sm" variant="outline" disabled={page <= 1 || loading} onClick={() => onPage(page - 1)}>Sebelumnya</Button><span className="text-xs text-slate-500">Halaman {page} dari {totalPages}</span><Button size="sm" variant="outline" disabled={page >= totalPages || loading} onClick={() => onPage(page + 1)}>Berikutnya</Button></div></CardContent></Card>
}
