CREATE TABLE IF NOT EXISTS ppdb_applicants (
    id VARCHAR(36) NOT NULL,
    wave_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    registration_path VARCHAR(50) NOT NULL,
    registration_level VARCHAR(50) NOT NULL,
    birth_place VARCHAR(100) NULL,
    birth_date DATE NULL,
    gender VARCHAR(10) NULL,
    nisn VARCHAR(50) NULL,
    parent_name VARCHAR(255) NULL,
    previous_school VARCHAR(255) NULL,
    major_choice VARCHAR(100) NULL,
    address TEXT NULL,
    status VARCHAR(50) DEFAULT 'pending_payment',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_ppdb_applicants_wave FOREIGN KEY (wave_id) REFERENCES ppdb_waves(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ppdb_applicants_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
